"""Snapshot content endpoint — returns the running-config text for a
given action's pre/post snapshot.

Phase E need: the action dict stored in confirmations contains directory
paths for `snapshot_pre` / `snapshot_post`, not the file content the
Config Preview page needs to render a diff. This endpoint bridges that
gap by reading the snapshot file from disk on demand.
"""

from __future__ import annotations

import re
from typing import Any

from fastapi import APIRouter, HTTPException

from backend.core.logging import get_logger
from backend.core.settings import get_settings

router = APIRouter(prefix="/api", tags=["snapshots"])
log = get_logger(__name__)

# Path-traversal guard. action_ids generated by propose_action use this shape
# (act_YYYYMMDD_<6 hex>); the regex stays tight intentionally — any `..`,
# slashes, or other path metacharacters fail validation BEFORE we construct
# a filesystem path.
_ACTION_ID_RE = re.compile(r"^act_[A-Za-z0-9_-]+$")
_VALID_PHASES = {"pre", "post"}


@router.get("/actions/{action_id}/snapshot/{phase}")
async def get_snapshot(action_id: str, phase: str) -> dict[str, Any]:
    """Return the running-config text captured at <phase> for <action_id>.

    Returns 422 on path-validation failure (invalid action_id or phase) —
    fail FAST before any filesystem touch.
    Returns 404 when the snapshot directory or file is missing.
    Returns 200 with {"action_id", "phase", "running_config"} on success.
    """
    if not _ACTION_ID_RE.match(action_id):
        raise HTTPException(status_code=422, detail="invalid action_id format")
    if phase not in _VALID_PHASES:
        raise HTTPException(status_code=422, detail="phase must be 'pre' or 'post'")

    settings = get_settings()
    snap_file = (
        settings.artifacts_dir / "device-snapshots" / action_id / phase / "running-config.txt"
    )
    if not snap_file.is_file():
        log.info(
            "snapshot_file_missing",
            action_id=action_id,
            phase=phase,
            path=str(snap_file),
        )
        raise HTTPException(status_code=404, detail="snapshot_not_found")

    try:
        content = snap_file.read_text(encoding="utf-8")
    except OSError as exc:
        log.warning("snapshot_read_failed", action_id=action_id, phase=phase, error=str(exc))
        raise HTTPException(status_code=500, detail="snapshot_read_failed") from exc

    return {
        "action_id": action_id,
        "phase": phase,
        "running_config": content,
    }
